version: '3.5'

services:
  mongodb:
    image: mongo:4.1.13
    container_name: mongodb
    command: mongod --auth
    networks:
      - mongo_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ~/.mongodb/data:/data/db
      - ~/.mongodb/init:/docker-entrypoint-initdb.d

  # mongoclient:
  #   image: mongoclient/mongoclient:2.2.0
  #   container_name: mongoclient
  #   networks:
  #     - mongo_network
  #   ports:
  #     - 27018:3000
  #   volumes:
  #     - ~/.mongodb/client:/data/db

networks:
  mongo_network:
    name: mongo_network
