version: '3.5'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    networks:
      - pg_network
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - /opt/docker/postgresql/data:/var/lib/postgresql/data
      - /opt/docker/postgresql/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - pg_network
    ports:
      - 5433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - /opt/docker/postgresql/pgadmin:/var/lib/pgadmin

networks:
  pg_network:
    name: pg_network